config/routes.rb
Rails.application.routes.draw do
  get '/login', to: 'sessions#new'
  post '/sessions', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/auth/github/callback', to: 'sessions#create'
  root 'site#index'
  get '/about', to: 'site#about'

  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]
  resources :authors do
    resources :books, only: [:new, :create, :show, :index]
  end
  resources :order_items
  post '/order_items/create/:id', to: 'orderitems#create', as: 'add_book'

  resources :books, only: [:show, :index]
  resources :authors, only: [:show, :index]
  get '/authors_list', to: 'authors#authors_list'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books
  scope :alphabetical, -> {order(name: :asc).limit(10)}
  scope :starts_with, -> (name) { where("name like ?", "#{name}%")}

  def first_name
    first_name = self.name.split(' ', 2).first
  end

  def family_name
    family_name = self.name.split(' ', 2).last
  end

  def self.sorted_family_names
    names = []
    self.all.map do |author|
      names << author.family_name
    end
    names.sort
  end

  def self.most_published
    self.all.sort_by { |author| author.books.size}.reverse
  end

end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :authorize

  def index
    @authors = Author.all
  end

  def show
    @author = Author.find_by(id: params[:id])
    @books = @author.books
    @order_item = current_user.cart.order_items.new
  end

  def authors_list
    @authors = Author.all.most_published
  end

end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/authors_list.html.erb
<br><br><% @authors.each do |author| %>
  Author Name: <%= link_to author.name, author_path(author) %><br>
  <p>Published Books: <%= author.books.size %><p><br>
    <% author.books.each do |book| %>
      Title: <%= link_to book.title, book_path(book) %><br>
    <% end %>
<% end %>

app/views/authors/show.html.erb
<img style="-webkit-user-select: none;cursor: zoom-in;" src="https://images.wisegeek.com/two-shelves-of-books.jpg" width="1300" height="300">

<h2><%= @author.name %></h2>

<% @author.books.each do |book| %>
  <%= link_to image_tag("https://www.ioba.org/pages/wp-content/uploads/2011/12/alledgesgilt.jpg"), book_path(book) %>
  <strong><h3> Title: <%= link_to book.title, author_book_path(@author, book) %></h3></strong>
  <strong><p> Genre: <%= book.genre %></p></strong>

  <% if !book.price.blank? %>
    <strong><p> Price: <%= number_to_currency book.price %></p></strong>
  <% end %>
  <% if !book.summary.blank? %>
    <strong><p> Summary: <%= book.summary %></p></strong>
  <% end %>

  <%= form_for @order_item do |f| %>
    <%= f.hidden_field :book_id, value: book.id %>
    <%= f.number_field :quantity %>
    <%= f.submit "Add to cart"%>
  <% end %><br>
<% end %>

<%= link_to "Create Custom Order", new_author_book_path(@author) %>
<%= link_to "See Author's Published Works", authors_list_path %>

<h3><%= link_to "Home", root_path %></h3>