config/routes.rb
Rails.application.routes.draw do
  get '/login', to: 'sessions#new'
  post '/sessions', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/auth/github/callback', to: 'sessions#create'
  root 'site#index'
  get '/about', to: 'site#about'

  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]
  resources :authors do
    resources :books, only: [:new, :create, :show, :index]
  end
  resources :order_items
  post '/order_items/create/:id', to: 'orderitems#create', as: 'add_book'

  resources :books, only: [:show, :index]
  resources :authors, only: [:show, :index]
  get '/authors_list', to: 'authors#authors_list'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :cart
  belongs_to :book
  scope :created_before, -> (time) {where("created_at < ?", time) }
  scope :most_popular, -> {order(quantity: :desc).limit(3)}

  def book_title
    self.book.title
  end

  def book_price
    self.book.price
  end

  def book_summary
    self.book.summary
  end

  def author_name
    self.book.author.name
  end

  def calculate_total
    self.cart.order_items.collect { |oi| oi.book.price * oi.quantity }.sum
  end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  before_action :authorize
  before_action :logged_in
  
  def index
    @order_items = current_cart.order_items
    @total_cost = calculate_total
  end

  def create
   @item = current_cart.order_items.build(item_params)
   @item.save
   session[:cart_id] = current_user.cart.id
   redirect_to order_items_path
  end

  def destroy
    @order = current_cart
    @item = @order.order_items.find(params[:id])
    @item.destroy
    @order.save
    redirect_to order_items_path
  end

  private
  def item_params
    params.require(:order_item).permit(:quantity, :book_id)
  end

  def calculate_total
    @total_cost = current_cart.order_items.collect { |oi| oi.book.price * oi.quantity }.sum
  end
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/views/order_items/index.html.erb
<h3><%= current_user.name.capitalize %>'s Shopping Cart </h3>
<% if @order_items.any? %>
  <% @order_items.each do |item| %>
    <p>Title: <%= item.book.title %> | <%= link_to "Delete", order_item_path(item), :data => {:confirm => "Are You Sure?", :method => "delete"} %></p>
    <p> Price: <%= number_to_currency item.book.price %> | Quantity: <%= item.quantity %> | Total Price: <%= number_to_currency (item.book.price * item.quantity) %></p>
  <% end %>
  <p>Grand Total: <%= number_to_currency @total_cost %>
<% else %>
  <p>Your shopping cart is empty.</p>
<% end %>
<h3><%= link_to  "Home", root_path %></h3>